### ISSUE TITLE
Resolve duplicate posts

### ISSUE THREAD

**Issue by nickserv** [danamcc/danamcc.github.io#26]
Duplicate check scripts are done, waiting to review results with @danamcc.

**Comment by nickserv** [comment]
As of 18a335f:
- [x] A Work in Progress
- [x] Acceptance
- [x] Emptiness
- [x] Enlightenment
- [x] Freedom
- [x] God
- [x] Happiness
- [x] Healing
- [x] I Am
- [x] Ignorance
- [x] Inside:Outside
- [x] Life and Death
- [x] Living
- [x] Love
- [x] Perfection
- [x] Presence
- [x] Relationships
- [x] Remembrance
- [x] Truth
- [x] Two Moments
- [x] Words
- [x] Your Picture

**Comment by danamcc** [comment]
I rule!
