### ISSUE TITLE
Consider replacing Prose with a different headless CMS

### ISSUE THREAD

**Issue by nickserv** [danamcc/danamcc.github.io#74]
## Alternatives
- [Netlify CMS](https://www.netlifycms.org/)
- [Forestry](https://forestry.io/)

## Resources
- https://www.netlifycms.org/docs/add-to-your-site/
- https://github.com/netlify-templates/jekyll-netlify-cms

**Comment by danamcc** [comment]
Thanks! Maybe at some point you could show me what it can do that Prose
can't.

**Comment by nickmccurdy** [comment]
Note that Netlify CMS is not a headless CMS, which would make it much easier to switch to compared to full headless CMSes like Contenful and GraphCMS (which expose their own APIs for content instead of editing files through a repo like Prose and GitHub do).

**Comment by nickmccurdy** [comment]
Resources:
- https://www.netlifycms.org/docs/add-to-your-site/
- https://github.com/netlify-templates/jekyll-netlify-cms
